### ISSUE TITLE
Add "How to Play" screen to show letter highlight styles

### ISSUE THREAD

**Issue by markaudacity** [RobbieNesmith/PalmWordle#13]
Great to have different shapes so I can play on my Palm Vx, but which shape means which type of match? 😅

**Comment by RobbieNesmith** [comment]
Hey thanks for playing!

In the main view, the rounded squares represent letters that are in the word but in the wrong place (yellow in color Wordle) and the thick bordered non-rounded squares represent letters that are in the correct place (green in color Wordle). Then letters with no border are not in the word at all.

In the keyboard view, the "yellow" and "green" ones are the same, but letters that are not in the word are inverted on a black background.

I should add a help menu that demonstrates the letter highlights.
Also #7 (Screenshot in the README)  could help new players understand the color/shape scheme
