### ISSUE TITLE
Can't enter a guess on Palm Tungsten E2

### ISSUE THREAD

**Issue by HubeCubes** [RobbieNesmith/PalmWordle#9]
Hello! Not sure if I'm missing something, but I can't seem to enter any guesses when playing on my Palm Tungsten E2. I am not sure if I'm supposed to be pressing a button or swiping a certain way. Any help would be appreciated! :)

**Comment by RobbieNesmith** [comment]
Hi! Thanks for trying out the app. Are you unable to enter letters or unable to submit a guess? Submitting a guess is done by writing the graffiti stroke for enter.

Unfortunately I don't have a Tungsten E2 to test on :( What OS version is installed on it?

**Comment by HubeCubes** [comment]
Oh! Nevermind! I forgot the return key stroke after all these years 😂. Works perfectly now that I'm doing it right. 

Cheers, and thanks for your hard work!

**Comment by RobbieNesmith** [comment]
Phew! Glad it's working! I clarified how to submit a guess on the "how to play" form and also now you can submit with the center button of the 5 way D-Pad of the T2!

**Comment by HubeCubes** [comment]
Just tried it-- works w/ the center button on the E2!
